(()=>{'use strict';
const DB='debtDiffDB',VER=1,OPS='operations',META='meta';let db,ops=[],meta={nameA:'Человек 1',nameB:'Человек 2',theme:'dark',lastBackupAt:null,statsLimit:'6'};
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:2}).format(Number(n)||0),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const panelIds=['formSection','historySection','analyticsSection','peopleSection','toolsSection'];
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(OPS))d.createObjectStore(OPS,{keyPath:'id'});if(!d.objectStoreNames.contains(META))d.createObjectStore(META,{keyPath:'key'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function allOps(){return new Promise((res,rej)=>{const r=tx(OPS).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});}
function putOp(o){return new Promise((res,rej)=>{const r=tx(OPS,'readwrite').put(o);r.onsuccess=res;r.onerror=()=>rej(r.error);});}
function delOp(id){return new Promise((res,rej)=>{const r=tx(OPS,'readwrite').delete(id);r.onsuccess=res;r.onerror=()=>rej(r.error);});}
function clearOps(){return new Promise((res,rej)=>{const r=tx(OPS,'readwrite').clear();r.onsuccess=res;r.onerror=()=>rej(r.error);});}
function getMeta(){return new Promise((res,rej)=>{const r=tx(META).get('main');r.onsuccess=()=>res(r.result?.value||{});r.onerror=()=>rej(r.error);});}
function saveMeta(){return new Promise((res,rej)=>{const r=tx(META,'readwrite').put({key:'main',value:meta});r.onsuccess=res;r.onerror=()=>rej(r.error);});}
function parseMoney(v){return Number(String(v).replace(/\s/g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0}
function setNow(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('dateInput').value=d.toISOString().slice(0,16)}
function applyTheme(){const light=meta.theme==='light';document.body.classList.toggle('light',light)}
function scrollToTarget(id){const el=$(id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});}
function closePanels(){panelIds.forEach(id=>$(id)?.classList.add('hidden'));document.querySelectorAll('.panel-section').forEach(el=>el.classList.remove('panel-open','form-card-active'));}
function openPanel(id,{focus=false}={}){panelIds.forEach(pid=>{const el=$(pid);if(!el)return;const show=pid===id;el.classList.toggle('hidden',!show);el.classList.toggle('panel-open',show);});scrollToTarget(id);if(id==='formSection'){$('formSection').classList.add('form-card-active');if(focus)setTimeout(()=>{$('amountInput')?.focus();},300);}}
function focusTransaction(){openPanel('formSection',{focus:true});}
async function load(){db=await openDB();meta={...meta,...await getMeta()};ops=(await allOps()).sort((a,b)=>new Date(b.date)-new Date(a.date));$('nameA').value=meta.nameA;$('nameB').value=meta.nameB;$('statsLimit').value=meta.statsLimit||'6';applyTheme();setNow();bind();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}
function bind(){['nameA','nameB'].forEach(id=>$(id).addEventListener('change',async()=>{meta[id]=$(id).value.trim()||meta[id];await saveMeta();render();}));$('statsLimit').addEventListener('change',async()=>{meta.statsLimit=$('statsLimit').value;await saveMeta();render();});$('themeBtn').onclick=async()=>{meta.theme=document.body.classList.contains('light')?'dark':'light';applyTheme();await saveMeta();};document.querySelectorAll('.nav-row').forEach(b=>b.onclick=()=>{if(b.dataset.target==='formSection')focusTransaction();else openPanel(b.dataset.target)});document.querySelectorAll('[data-close-panel]').forEach(b=>b.onclick=closePanels);$('fabAdd').onclick=focusTransaction;$('saveBtn').onclick=saveCurrent;$('cancelEditBtn').onclick=cancelEdit;$('exportJsonBtn').onclick=exportJSON;$('quickBackupBtn').onclick=exportJSON;$('exportCsvBtn').onclick=exportCSV;$('importFile').onchange=importFile;$('clearBtn').onclick=clearAll;}
async function saveCurrent(){const amount=parseMoney($('amountInput').value)*Number($('signSelect').value);if(!amount){alert('Введите сумму');return}const id=$('editId').value||uid();const o={id,side:$('sideSelect').value,amount,date:$('dateInput').value?new Date($('dateInput').value).toISOString():new Date().toISOString(),comment:$('commentInput').value.trim()};await putOp(o);ops=(await allOps()).sort((a,b)=>new Date(b.date)-new Date(a.date));cancelEdit(false);closePanels();render();}
function cancelEdit(reset=true){$('editId').value='';$('formTitle').textContent='Новая транзакция';$('saveBtn').textContent='Сохранить';$('cancelEditBtn').classList.add('hidden');if(reset){$('amountInput').value='';$('commentInput').value='';$('signSelect').value='1';setNow();}else{$('amountInput').value='';$('commentInput').value='';$('signSelect').value='1';setNow();}}
function edit(o){$('editId').value=o.id;$('formTitle').textContent='Изменить транзакцию';$('saveBtn').textContent='Обновить';$('cancelEditBtn').classList.remove('hidden');$('sideSelect').value=o.side;$('signSelect').value=o.amount<0?'-1':'1';$('amountInput').value=Math.abs(o.amount);const d=new Date(o.date);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('dateInput').value=d.toISOString().slice(0,16);$('commentInput').value=o.comment||'';focusTransaction();}
async function remove(id){if(!confirm('Удалить запись?'))return;await delOp(id);ops=ops.filter(o=>o.id!==id);render();}
async function clearAll(){if(!confirm('Очистить всю историю? Сначала лучше сделайте backup.'))return;await clearOps();ops=[];render();}
function render(){const nameA=$('nameA').value||'Человек 1',nameB=$('nameB').value||'Человек 2';$('sideSelect').options[0].textContent=nameA;$('sideSelect').options[1].textContent=nameB;const a=ops.filter(o=>o.side==='a').reduce((s,o)=>s+Number(o.amount||0),0),b=ops.filter(o=>o.side==='b').reduce((s,o)=>s+Number(o.amount||0),0),d=a-b;$('totalA').textContent=fmt(a);$('totalB').textContent=fmt(b);$('diffAmount').textContent=fmt(Math.abs(d));$('diffText').textContent=d>0?`${nameA} больше на ${fmt(d)}`:d<0?`${nameB} больше на ${fmt(Math.abs(d))}`:'Пока одинаково.';$('statusText').textContent=`Записей: ${ops.length}. Данные хранятся на этом устройстве.`;const ta=Math.abs(a),tb=Math.abs(b),sum=ta+tb||1;$('splitA').style.width=`${ta/sum*100}%`;$('splitB').style.width=`${tb/sum*100}%`;$('splitA').style.background='linear-gradient(90deg,#83cf87,#a8e0a6)';$('splitB').style.background='linear-gradient(90deg,#df5d73,#ef7386)';renderBackupWarn();renderStats(nameA,nameB);renderHistory(nameA,nameB);}
function renderBackupWarn(){const last=meta.lastBackupAt?new Date(meta.lastBackupAt).getTime():0;const old=!last||Date.now()-last>3*24*60*60*1000;$('backupWarn').classList.toggle('hidden',!old||ops.length===0)}
function monthKey(date){const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function monthTitle(key){const [y,m]=key.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}
function renderStats(nameA,nameB){const box=$('monthlyStats');if(!box)return;box.innerHTML='';if(!ops.length){$('monthDiff').textContent=fmt(0);$('monthText').textContent='Нет записей';$('weekDiff').textContent=fmt(0);$('weekText').textContent='Нет записей';$('monthDiffSummary').textContent=fmt(0);$('monthTextSummary').textContent='Нет записей';$('avgMonthDiff').textContent=fmt(0);$('avgMonthText').textContent='По всем месяцам';box.innerHTML='<p class="small">После добавления записей здесь появится статистика по месяцам.</p>';return}
 const map=new Map();ops.forEach(o=>{const k=monthKey(o.date);if(!map.has(k))map.set(k,{a:0,b:0,count:0});const m=map.get(k);if(o.side==='a')m.a+=Number(o.amount)||0;else m.b+=Number(o.amount)||0;m.count++;});
 const months=[...map.entries()].sort((x,y)=>y[0].localeCompare(x[0])).map(([key,v])=>({...v,key,diff:v.a-v.b}));const currentKey=monthKey(new Date());const cur=map.get(currentKey)||{a:0,b:0,count:0};const curDiff=cur.a-cur.b;$('monthDiff').textContent=fmt(Math.abs(curDiff));$('monthText').textContent=curDiff>0?`${nameA} больше в этом месяце`:curDiff<0?`${nameB} больше в этом месяце`:'В этом месяце одинаково';$('monthDiffSummary').textContent=fmt(Math.abs(curDiff));$('monthTextSummary').textContent=$('monthText').textContent;const weekStart=new Date();weekStart.setDate(weekStart.getDate()-6);weekStart.setHours(0,0,0,0);const w=ops.filter(o=>new Date(o.date)>=weekStart).reduce((acc,o)=>{if(o.side==='a')acc.a+=Number(o.amount)||0;else acc.b+=Number(o.amount)||0;return acc;},{a:0,b:0});const wDiff=w.a-w.b;$('weekDiff').textContent=fmt(Math.abs(wDiff));$('weekText').textContent=wDiff>0?`${nameA} больше за неделю`:wDiff<0?`${nameB} больше за неделю`:'За неделю одинаково';
 const avg=months.reduce((s,m)=>s+Math.abs(m.diff),0)/months.length;$('avgMonthDiff').textContent=fmt(avg);$('avgMonthText').textContent=`Средняя разница за ${months.length} мес.`;
 const limit=$('statsLimit')?.value||'6';const shown=limit==='all'?months:months.slice(0,Number(limit));const max=Math.max(...shown.map(m=>Math.max(Math.abs(m.a),Math.abs(m.b),Math.abs(m.diff))),1);
 shown.forEach(m=>{const row=document.createElement('div');row.className='month-row';const winner=m.diff>0?`${nameA} +${fmt(m.diff)}`:m.diff<0?`${nameB} +${fmt(Math.abs(m.diff))}`:'ровно';row.innerHTML=`<div class="month-top"><b>${monthTitle(m.key)}</b><span>${m.count} зап.</span></div><div class="month-grid"><span>${nameA}</span><strong>${fmt(m.a)}</strong><i style="width:${Math.min(100,Math.abs(m.a)/max*100)}%"></i></div><div class="month-grid"><span>${nameB}</span><strong>${fmt(m.b)}</strong><i style="width:${Math.min(100,Math.abs(m.b)/max*100)}%"></i></div><div class="month-result">Итог: ${winner}</div>`;box.appendChild(row);});}
function renderHistory(nameA,nameB){const list=$('historyList');list.innerHTML='';if(!ops.length){list.innerHTML='<p class="small">Записей пока нет.</p>';return}const tpl=$('rowTemplate');ops.forEach(o=>{const n=tpl.content.cloneNode(true);n.querySelector('.row-title').textContent=o.side==='a'?nameA:nameB;n.querySelector('.row-meta').textContent=new Date(o.date).toLocaleString('ru-RU');n.querySelector('.row-comment').textContent=o.comment||'';n.querySelector('.row-amount').textContent=fmt(o.amount);n.querySelector('.edit-btn').onclick=()=>edit(o);n.querySelector('.delete-btn').onclick=()=>remove(o.id);list.appendChild(n);});}
function download(name,type,content){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function exportJSON(){meta.lastBackupAt=new Date().toISOString();await saveMeta();const data={version:1,app:'debt-diff-app',createdAt:new Date().toISOString(),meta,operations:ops};download(`debt-diff-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json;charset=utf-8',JSON.stringify(data,null,2));renderBackupWarn();}
function esc(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function exportCSV(){const nameA=$('nameA').value||'Человек 1',nameB=$('nameB').value||'Человек 2';let s='Дата;Сторона;Сумма;Комментарий\n';ops.slice().reverse().forEach(o=>{s+=[new Date(o.date).toLocaleString('ru-RU'),o.side==='a'?nameA:nameB,String(o.amount).replace('.',','),o.comment||''].map(esc).join(';')+'\n'});download('debt-diff.csv','text/csv;charset=utf-8','\ufeff'+s)}
async function importFile(e){const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());let imported=[];if(Array.isArray(data.operations)){imported=data.operations.map(o=>({id:o.id||uid(),side:o.side==='b'?'b':'a',amount:Number(o.amount)||0,date:o.date||new Date().toISOString(),comment:o.comment||''}));if(data.meta){meta={...meta,...data.meta};}}
else if(Array.isArray(data.transactions)){imported=data.transactions.map(t=>({id:t.id||uid(),side:t.type==='expense'?'b':'a',amount:Number(t.amountNative)||0,date:t.dateISO||new Date().toISOString(),comment:[t.category,t.walletName].filter(Boolean).join(' / ')}));}
else throw new Error('Неизвестный формат');if(!imported.length){alert('В файле нет записей');return}if(!confirm(`Импортировать ${imported.length} записей?`))return;for(const o of imported)await putOp(o);await saveMeta();ops=(await allOps()).sort((a,b)=>new Date(b.date)-new Date(a.date));$('nameA').value=meta.nameA;$('nameB').value=meta.nameB;$('statsLimit').value=meta.statsLimit||'6';render();alert('Импорт готов');}catch(err){alert('Ошибка импорта: '+err.message)}finally{e.target.value=''}}
load().catch(e=>{console.error(e);$('statusText').textContent='Ошибка запуска: '+e.message});
})();
